version: '3.2'

volumes:
  mariadb_data:
  node_modules:

services:
  mariadb:
    image: mariadb:focal
    # ports:
    #   - 3306:3306
    restart: always
    volumes:
      - mariadb_data:/var/lib/mysql
    env_file:
      - .env

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 9349:9349
    env_file:
      - .env
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    restart: always
    depends_on:
      - mariadb
    command: >
      bash -c "if [ $$DEBUGGER == 'true' ]; then
        /wait-for-it.sh mariadb:3306 --strict -- yarn start:debug;
      else
        /wait-for-it.sh mariadb:3306 --strict -- yarn start:dev;
      fi"
